apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          env:
          - name: MASTER
            value: "true"
          ports:
            - containerPort: 6379
          volumeMounts:
          - mountPath: /data
            name: redisdb
      volumes:
      - name: redisdb
        persistentVolumeClaim:
          claimName: redis-claim
---
apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379